### ISSUE TITLE
Emit a signal that is emitted when message is logged.

### ISSUE THREAD

**Issue by albinaask** [DawnGroveStudios/GodotLogger#13]
I'm implementing an external log window for when my project runs without the editor, and would like to use your addon for my logging needs. But in order for the log window to pick up the messages sent to the log messages a signal would be in order. I can of course just add it to my instance of the addon, but thought it would be something that more people would benefit from. Would you mind me adding this to your addon?

**Comment by Seann-Moser** [comment]
Of course!

**Comment by Seann-Moser** [comment]
I have pushed changes to include `signal log_message(type, message)` and it is included in the latest release.
