### ISSUE TITLE
Out of date assetlib version

### ISSUE THREAD

**Issue by Loufe** [DawnGroveStudios/GodotLogger#23]
Hi there, 

I noticed the version of this plugin in the godot assetlib is out of date. Could I ask you to update it to the most recent version? It's still on a version from last october.

Thank you!

In passing, this is likely overkill but an option for auto-updating would be: https://github.com/myyk/godot-plugin-updater

**Comment by Seann-Moser** [comment]
I have just updated it to the most recent version, should be out sometime tomorrow
