### ISSUE TITLE
License mismatch: MIT or GPL-3?

### ISSUE THREAD

**Issue by Fireforge** [DawnGroveStudios/GodotLogger#4]
[The Godot Asset Library lists your asset as MIT licensed](https://godotengine.org/asset-library/asset/1975), but this Github repo's LICENSE file says it's GPL-3.0. While both are open source, these two licenses are _very_ different, as one is copyleft and the other is permissive. Please clarify which license you really want:

- If you want to make sure anyone who uses this code _must_ make their Godot game's source code available also under GPL-3.0 or compatible license, please update the Godot Asset Library and list it as GPL-3.0 (or remove it from the Asset Library).

- If you want people to have maximum freedom, in your next version please update the LICENSE file of this Github repo to the MIT license text.

**Comment by Seann-Moser** [comment]
I have just pushed up license changes to use MIT and requested an update to version 1.0.4. So the license should be resolved once the new version is approved.

**Comment by Fireforge** [comment]
Awesome, thank you! 🙂
